Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2021-09, with the labels that each got.

#596 Feature/v2 clients integration
  docker-compose-api-only.yml
  talentmap_api/fsbid/services/client.py
  talentmap_api/settings.py
Labels: dual merge, Release

#595 Bureau to /cyclepositions
  talentmap_api/fsbid/services/available_positions.py
  talentmap_api/fsbid/services/bureau.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/employee.py
Labels: Release

#599 Fix for SND export value
  talentmap_api/fsbid/services/common.py
Labels: bug
