Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2021-12, with the labels that each got.

#639 ubw-hs mapping
  talentmap_api/fsbid/services/bureau.py
Labels: integration :wrench:

#640 Employee fixes
  talentmap_api/fsbid/services/client.py
Labels: integration :wrench:

#644 sorting and single filter working
  talentmap_api/permission/views/user.py
Labels: dual merge

#645 Use hru_id to fetch employee profile report
  docker-compose-api-only.yml
  talentmap_api/fsbid/services/client.py
Labels: dual merge

#648 Agenda Item History integration
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/classifications.py
  talentmap_api/fsbid/services/common.py
Labels: dual merge, WIP

#650 agenda item history export
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/urls/agenda.py
  talentmap_api/fsbid/views/agenda.py
Labels: dual merge, WIP
