Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2021-08, with the labels that each got.

#584 Competing rank indicator is filtered to only available positions
  talentmap_api/bidding/migrations/0007_bidhandshake_bid_cycle_id.py
  talentmap_api/bidding/models.py
  talentmap_api/bidding/views/bidhandshake.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/reference.py
Labels: dual merge

#577 Integrate with new POST request for AP with feature flag
  docker-compose-api-only.yml
  docker-compose.yml
  talentmap_api/fsbid/services/available_positions.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/settings.py
Labels: dual merge

#582 non-cdo classifications set up
  talentmap_api/fsbid/services/classifications.py
  talentmap_api/fsbid/services/reference.py
  talentmap_api/fsbid/urls/classifications.py
  talentmap_api/fsbid/views/classifications.py
  talentmap_api/fsbid/views/reference.py
  talentmap_api/urls.py
Labels: dual merge

#546 rework - 👵
  talentmap_api/available_positions/views/available_position.py
Labels: aging :older_adult:

#591 Add export endpoint for glossary
  talentmap_api/glossary/urls/glossary.py
  talentmap_api/glossary/views/glossary.py
Labels: Release

#589 Exclude Revoked HS from bidder bid list
  talentmap_api/bidding/services/bidhandshake.py
  talentmap_api/fsbid/services/bid.py
Labels: Release

#590 Update so that bidder can only accept one handshake per bid cycle
  talentmap_api/bidding/views/bidhandshake.py
  talentmap_api/fsbid/services/bid.py
Labels: Release

#592 Filter out null'd/empty arrays from POST
  talentmap_api/fsbid/services/available_positions.py
Labels: Release
