Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-11, with the labels that each got.

#861 TM-5009 Assignment History Status
  talentmap_api/fsbid/services/assignment_history.py
Labels: size/XS

#862 error handling for manage bid seasons
  talentmap_api/fsbid/services/manage_bid_seasons.py
Labels: dual merge

#863 Update size-label.yml for api
  .github/workflows/size-label.yml
Labels: size/XS

#856 PM & PMD Create/Edit
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/admin_panel.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/remark.py
  talentmap_api/fsbid/views/admin_panel.py
Labels: size/L

#859 [TM-5024] Run Panel Follow-Up (Miscellaneous)
  talentmap_api/fsbid/services/admin_panel.py
Labels: size/XS

#852 TM-4910-Bureau-Exception-List-API-Integration
  talentmap_api/fsbid/services/bureau_exception_list.py
  talentmap_api/fsbid/urls/bureau_exception_list.py
  talentmap_api/fsbid/views/bureau_exception_list.py
  talentmap_api/urls.py
Labels: size/L

#836 [TM-4845] Position Classifications Integration
  talentmap_api/fsbid/services/position_classifications.py
  talentmap_api/fsbid/services/reference.py
  talentmap_api/fsbid/urls/position_classifications.py
  talentmap_api/fsbid/views/position_classifications.py
  talentmap_api/fsbid/views/reference.py
  talentmap_api/urls.py
Labels: size/L

#870 TM-5070 Pt1 - Renaming Bureau Exceptions functions, file names, and comments
  talentmap_api/fsbid/services/bureau_exceptions.py
  talentmap_api/fsbid/urls/bureau_exception_list.py
  talentmap_api/fsbid/urls/bureau_exceptions.py
  talentmap_api/fsbid/views/bureau_exception_list.py
  talentmap_api/urls.py
Labels: dual merge, size/L

#851 Release 11.2
  TM_Version.txt
  docker-compose-api-only.yml
  docker-compose-cloud.yml
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/services/job_categories.py
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/fsbid/views/employee.py
  talentmap_api/fsbid/views/publishable_positions.py
  talentmap_api/settings.py
Labels: do not merge, dual merge, size/M

#871 [TM-5059] Panel Meeting Agenda Remarks - Hold
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS

#874 TM-4999-Agenda-BE
  talentmap_api/fsbid/services/client.py
Labels: size/XS, Approved :heavy_check_mark:

#872 TM-5070 Pt2 - BEL Refactor
  talentmap_api/fsbid/services/bureau_exceptions.py
  talentmap_api/fsbid/urls/bureau_exceptions.py
  talentmap_api/fsbid/views/bureau_exceptions.py
Labels: dual merge, size/L, Approved :heavy_check_mark:
