Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-05, with the labels that each got.

#800 Handle suffix
  talentmap_api/fsbid/services/agenda_employees.py
Labels: size/XS, Approved :heavy_check_mark:

#797 Fix for eta for retire
  talentmap_api/fsbid/services/agenda.py
Labels: dual merge, size/XS, Approved :heavy_check_mark:

#801 TM-4323: changing order of names in export
  talentmap_api/fsbid/services/client.py
Labels: size/XS, Approved :heavy_check_mark:

#799 TM-4326, update backend to handle TOD input
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/reference.py
  talentmap_api/fsbid/urls/reference.py
  talentmap_api/fsbid/views/reference.py
Labels: size/S, Approved :heavy_check_mark:

#806 TM-4449 Feature/ai validation legs
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: dual merge, size/M, Approved :heavy_check_mark:

#808 Add GSA locations ep
  talentmap_api/fsbid/services/reference.py
  talentmap_api/fsbid/urls/reference.py
  talentmap_api/fsbid/views/reference.py
Labels: dual merge, size/M, Approved :heavy_check_mark:
