Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-10, with the labels that each got.

#838 TM-4848, Manage Post Access API
  talentmap_api/fsbid/services/post_access.py
  talentmap_api/fsbid/views/post_access.py
Labels: WIP, size/M, Approved :heavy_check_mark:

#842 TM-4863, Manage Bid Seasons API
  talentmap_api/fsbid/services/manage_bid_seasons.py
  talentmap_api/fsbid/urls/manage_bid_seasons.py
  talentmap_api/fsbid/views/manage_bid_seasons.py
  talentmap_api/urls.py
Labels: size/L, Approved :heavy_check_mark:

#849 TM-4846: Job Category support for saving new category
  talentmap_api/fsbid/services/job_categories.py
  talentmap_api/fsbid/urls/job_categories.py
  talentmap_api/fsbid/views/job_categories.py
Labels: size/L, Approved :heavy_check_mark:

#854 TM-2493, TM-4998 add combined TOD to AIM page
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS

#853 Job Categories: Removing logging statements
  talentmap_api/fsbid/services/job_categories.py
Labels: size/XS, Approved :heavy_check_mark:

#855 TM-4991-Panel-View-BE
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS

#850 [TM-4843] Run Panel Integration
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/admin_panel.py
  talentmap_api/fsbid/urls/admin_panel.py
  talentmap_api/fsbid/views/admin_panel.py
Labels: size/XL, Approved :heavy_check_mark:
