Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-04, with the labels that each got.

#788 Fixed with Elizabeth's insights
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#789 Initial remapping with single call for client data
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/client.py
Labels: dual merge, Release, size/S, Approved :heavy_check_mark:

#790 cast to int first
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/client.py
Labels: Release, size/XS

#791 Optimize PMA Client Lookup
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#794 TM-4265, add suffix to agenda search name
  talentmap_api/fsbid/services/agenda_employees.py
Labels: aging :older_adult:, size/XS, Approved :heavy_check_mark:

#795 denoting legacy remarks
  talentmap_api/fsbid/services/common.py
Labels: size/M, Approved :heavy_check_mark:
