Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-07, with the labels that each got.

#818 Private Profile and Redacted URL Set Up
  .circleci/config.yml
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/views/client.py
  talentmap_api/user_profile/serializers.py
Labels: dual merge, size/S, Approved :heavy_check_mark:

#820 TM-4594: Consolidating two ted variables
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
  talentmap_api/fsbid/views/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#822 leg agenda validator
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS, Approved :heavy_check_mark:

#821 defaulting mutuallyExclusive to N TM-4448
  talentmap_api/fsbid/services/admin_panel.py
Labels: size/XS, Approved :heavy_check_mark:

#819 Update validator and post req for duty station on sep
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/services/reference.py
Labels: dual merge, size/L

#823 TM-3088, sort ass history by start date
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/views/assignment_history.py
Labels: size/XS, Approved :heavy_check_mark:
