Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-12, with the labels that each got.

#878 Edit/Create PMI
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/views/agenda.py
Labels: size/M

#880 Bel updates
  talentmap_api/fsbid/services/bureau_exceptions.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/views/bureau_exceptions.py
Labels: size/S, Approved :heavy_check_mark:

#876 TM-5197-Panel-Agenda-User-Centric-Data-BE
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/common.py
Labels: size/S, Approved :heavy_check_mark:

#883 Update/create edit ai
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
  talentmap_api/fsbid/services/common.py
Labels: size/L

#881 [TM-4919] Bidding Tool Integration
  talentmap_api/fsbid/services/bidding_tool.py
  talentmap_api/fsbid/urls/bidding_tool.py
  talentmap_api/fsbid/views/bidding_tool.py
  talentmap_api/urls.py
Labels: size/XL, Approved :heavy_check_mark:

#885 [TM-4919] Bidding Tool Integration Patches v1
  talentmap_api/fsbid/services/bidding_tool.py
  talentmap_api/fsbid/views/bidding_tool.py
Labels: size/XS, Approved :heavy_check_mark:
