Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-08, with the labels that each got.

#827 Feature/create edit remarks
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/remark.py
  talentmap_api/fsbid/urls/remark.py
  talentmap_api/fsbid/views/remark.py
  talentmap_api/urls.py
Labels: dual merge, Release, size/L, Approved :heavy_check_mark:

#828 TM Version 11.0
  TM_Version.txt
Labels: dual merge, Release, size/XS

#825 TM-4521: Pay Plan field - Panel Agenda items
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/services/positions.py
Labels: size/XS, Approved :heavy_check_mark:

#831 TM-4894 emp profile to api call
  docker-compose-api-only.yml
  docker-compose-cloud.yml
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/urls/employee.py
  talentmap_api/fsbid/views/client.py
  talentmap_api/fsbid/views/employee.py
  talentmap_api/settings.py
  talentmap_api/user_profile/serializers.py
Labels: dual merge, size/M, Approved :heavy_check_mark:
