Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2023-09, with the labels that each got.

#832 TM-4847, Search Post Access API
  docker-compose-cloud.yml
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/post_access.py
  talentmap_api/fsbid/urls/post_access.py
  talentmap_api/fsbid/views/post_access.py
  talentmap_api/settings.py
  talentmap_api/urls.py
Labels: size/L, Approved :heavy_check_mark:

#839 Edit Remark
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/remark.py
  talentmap_api/fsbid/urls/remark.py
  talentmap_api/fsbid/views/remark.py
Labels: dual merge, size/M, Approved :heavy_check_mark:

#841 Fix Y vs True
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/remark.py
  talentmap_api/fsbid/views/remark.py
Labels: size/XS

#840 TM-4707: Job categories integration
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/job_categories.py
  talentmap_api/fsbid/services/post_access.py
  talentmap_api/fsbid/urls/job_categories.py
  talentmap_api/fsbid/views/job_categories.py
  talentmap_api/urls.py
Labels: size/L

#824 Publishable Positions Integration
  docker-compose-api-only.yml
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/fsbid/urls/publishable_positions.py
  talentmap_api/fsbid/views/publishable_positions.py
  talentmap_api/urls.py
Labels: dual merge, size/L, Approved :heavy_check_mark:

#843 Version release
  TM_Version.txt
  talentmap_api/fsbid/views/publishable_positions.py
Labels: size/XS

#845 Update org descr
  talentmap_api/fsbid/services/publishable_positions.py
Labels: size/XS, Approved :heavy_check_mark:

#846 Fix typo
  talentmap_api/fsbid/services/publishable_positions.py
Labels: size/XS

#844 11.1 Dev -> Staging
  TM_Version.txt
  docker-compose-api-only.yml
  docker-compose-cloud.yml
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/services/job_categories.py
  talentmap_api/fsbid/services/positions.py
  talentmap_api/fsbid/services/post_access.py
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/fsbid/services/remark.py
  talentmap_api/fsbid/urls/employee.py
  talentmap_api/fsbid/urls/job_categories.py
  talentmap_api/fsbid/urls/post_access.py
  talentmap_api/fsbid/urls/publishable_positions.py
  talentmap_api/fsbid/urls/remark.py
  talentmap_api/fsbid/views/client.py
  talentmap_api/fsbid/views/employee.py
  talentmap_api/fsbid/views/job_categories.py
  talentmap_api/fsbid/views/post_access.py
  talentmap_api/fsbid/views/publishable_positions.py
  talentmap_api/fsbid/views/remark.py
  talentmap_api/settings.py
  talentmap_api/urls.py
  talentmap_api/user_profile/serializers.py
Labels: size/XL, Approved :heavy_check_mark:

#847 response update - Search Post Access
  talentmap_api/fsbid/services/post_access.py
Labels: size/S, Approved :heavy_check_mark:

#848 response update - Job Categories
  talentmap_api/fsbid/services/job_categories.py
Labels: size/M, Approved :heavy_check_mark:
