Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-07, with the labels that each got.

#1026 TM-5970-Client-Profile-Export
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/client.py
Labels: size/M, Approved

#1029 TM-6302 add search flag for Critical Need
  talentmap_api/fsbid/filters.py
  talentmap_api/fsbid/services/available_positions.py
Labels: size/XS

#1030 TM-6150-Updated-TED
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/client.py
Labels: size/S, Approved

#1023 Release 13.0
  TM_Version.txt
Labels: do not merge, size/XS, Approved

#1028 [TM-6170] TM1 Notifications (Read Only)
  talentmap_api/fsbid/services/notifications.py
  talentmap_api/fsbid/urls/notifications.py
  talentmap_api/fsbid/views/notifications.py
  talentmap_api/urls.py
Labels: size/L, Approved

#1032 Bidding Tool: Read Only Roles
  talentmap_api/fsbid/views/bidding_tool.py
Labels: size/XS, Approved

#1033 Fix/bidding tool read
  talentmap_api/fsbid/urls/bidding_tool.py
  talentmap_api/fsbid/views/bidding_tool.py
Labels: size/S, Approved

#1035 hotfix none type for bureau exception
  talentmap_api/fsbid/services/bureau_exceptions.py
Labels: size/XS, Approved

#1036 Bureau User Access: Employee Profile
  talentmap_api/fsbid/views/employee.py
Labels: size/XS

#1037 Employee Profile: Add Post Users
  talentmap_api/fsbid/views/employee.py
Labels: size/S

#1039 PPos Position Classifications: Restrict Edit to Superuser
  talentmap_api/fsbid/views/position_classifications.py
Labels: size/XS

#1031 [TM-4911] TM1 Notifications (Edit Endpoints)
  talentmap_api/fsbid/services/notifications.py
  talentmap_api/fsbid/urls/notifications.py
  talentmap_api/fsbid/views/notifications.py
Labels: size/L, Approved

#1043 TM-5920, Bid Audit Data, API
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/M

#1042 [TM-4911] TM1 Notifications (Edit Endpoints)
  talentmap_api/fsbid/services/notifications.py
  talentmap_api/fsbid/urls/notifications.py
  talentmap_api/fsbid/views/notifications.py
Labels: size/L

#1045 Merge release 13 > dev
  talentmap_api/fsbid/services/bureau_exceptions.py
  talentmap_api/fsbid/urls/bidding_tool.py
  talentmap_api/fsbid/views/bidding_tool.py
  talentmap_api/fsbid/views/employee.py
  talentmap_api/fsbid/views/position_classifications.py
Labels: size/M, Approved
