Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-04, with the labels that each got.

#960 Release 12.1
  TM_Version.txt
Labels: size/XS, Approved

#967 adding skill code to export
  talentmap_api/fsbid/services/client.py
Labels: size/XS

#964 PP/Grade standardization
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/services/publishable_positions.py
Labels: size/M, Approved

#966 TM-5807, cycle date classifications
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
Labels: size/M, Approved

#963 [TM-5710] Projected Vacancy Integration Remediation
  talentmap_api/fsbid/services/admin_projected_vacancies.py
Labels: question, size/XS, Approved

#965 Update/create asg
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/services/positions.py
  talentmap_api/fsbid/urls/assignment_history.py
  talentmap_api/fsbid/views/assignment_history.py
Labels: size/XS, Approved

#972 [TM-5710] Projected Vacancy Edit Description Hotfix
  talentmap_api/fsbid/services/admin_projected_vacancies.py
Labels: size/XS, Approved

#973 TM-4995: PP export redo
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/fsbid/urls/publishable_positions.py
  talentmap_api/fsbid/views/publishable_positions.py
Labels: Approved Pending Feedback, size/M, Approved

#970 TM-5672 update cycle date classifications
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
Labels: size/M, Approved

#974 TM-5875, Bid Audit API
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
  talentmap_api/urls.py
Labels: size/L, Approved

#978 comment out not integrated fields
  talentmap_api/fsbid/services/publishable_positions.py
Labels: size/S, Approved

#979 TM-5874, Run Bid Audit
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/S, Approved
