Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-10, with the labels that each got.

#1084 Tm 6488 add eltoml
  talentmap_api/fsbid/services/positions.py
Labels: size/XS, Approved

#1086 TM-6581-API-Email-Comments
  talentmap_api/fsbid/services/client.py
Labels: size/S, Approved

#1083 Adding el_cdo role
  talentmap_api/common/management/commands/create_base_permissions.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/user_profile/management/commands/create_seeded_users.py
Labels: size/XS, Approved

#1085 Tm 6425 export button not working api
  TM_Version.txt
  talentmap_api/fsbid/services/client.py
Labels: size/XL, Approved

#1087 Release 14.0.0
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/services/notifications.py
Labels: size/S, Approved

#1088 Tm 2120 export el positions table
  talentmap_api/fsbid/views/positions.py
Labels: size/XS, Approved

#1089 TM-6510-CDO D3.0 (Panel Clients & Classifications) - API
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/urls/client.py
  talentmap_api/fsbid/views/client.py
Labels: size/M, Approved

#1091 TM-6403-CDO-Table-API
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/urls/client.py
  talentmap_api/fsbid/views/client.py
Labels: size/S, Approved

#1092 Tm 6618 update ability to filter panel meeting agendas api
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/common.py
Labels: size/S, Approved

#1090 [TM-6614] TM1 OPS Endpoints
  talentmap_api/fsbid/services/notifications.py
  talentmap_api/fsbid/urls/notifications.py
  talentmap_api/fsbid/views/notifications.py
Labels: size/L, Approved

#1095 update skill filter
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved
