Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-02, with the labels that each got.

#928 Remove unused loggers
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#929 TM-5480, separation location
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#886 TM-5308, TM-5413 initial fetch & create new cycle for Cycle Management Page
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
  talentmap_api/urls.py
Labels: size/L, Approved :heavy_check_mark:

#932 handle empties
  talentmap_api/fsbid/services/assignment_cycles.py
Labels: dual merge, size/M, Approved :heavy_check_mark:

#933 Create APIs for all maintain asg procs
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/urls/assignment_history.py
  talentmap_api/fsbid/views/assignment_history.py
Labels: size/L, Approved :heavy_check_mark:

#934 [TM-4680] Projected Vacancy Integration (Read)
  talentmap_api/fsbid/services/admin_projected_vacancies.py
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/post_access.py
  talentmap_api/fsbid/services/projected_vacancies.py
  talentmap_api/fsbid/urls/admin_projected_vacancies.py
  talentmap_api/fsbid/views/admin_projected_vacancies.py
  talentmap_api/urls.py
Labels: size/L, Approved :heavy_check_mark:

#927 TM-4819-BE-Org-Stat
  talentmap_api/fsbid/services/org_stats.py
  talentmap_api/fsbid/urls/org_stats.py
  talentmap_api/fsbid/views/org_stats.py
  talentmap_api/urls.py
Labels: size/L, Approved :heavy_check_mark:

#940 TM-4918-Org-Stats-Percents
  talentmap_api/fsbid/services/org_stats.py
Labels: size/XS, Approved :heavy_check_mark:

#937 to get
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: dual merge, Aging :older_adult:, size/S, Approved

#936 [TM-5389] Projected Vacancy Integration (Edit)
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/admin_projected_vacancies.py
  talentmap_api/fsbid/urls/admin_projected_vacancies.py
  talentmap_api/fsbid/views/admin_projected_vacancies.py
Labels: size/XL, Approved

#935 TM-4917: Manage EL Positions Integration
  talentmap_api/fsbid/services/positions.py
  talentmap_api/fsbid/urls/positions.py
  talentmap_api/fsbid/views/positions.py
Labels: size/L, Approved
