Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-09, with the labels that each got.

#1075 Tm 6433 re work panel meeting agendas page
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_employees.py
  talentmap_api/fsbid/services/common.py
Labels: do not merge, size/S, Approved

#1077 RWA/DETO Filtering API
  talentmap_api/fsbid/services/available_positions.py
  talentmap_api/fsbid/services/projected_vacancies.py
Labels: size/XS, Approved

#1079 TM-5228-Unassigned-Bidders-API
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/urls/client.py
  talentmap_api/fsbid/views/client.py
Labels: size/M, Approved

#1080 Add SQL script to assign superuser role to specific user
  talentmap_db_queries/add-superuser-to-talentmap.sql
Labels: size/XS, Approved

#1081 Tm 6488 add eltoml
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/positions.py
  talentmap_api/fsbid/urls/positions.py
  talentmap_api/fsbid/views/positions.py
Labels: size/M, Approved
