Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-05, with the labels that each got.

#984 TM-5878, Update Bid Audit
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/S, Approved

#977 Civil Service Emp Profile
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/urls/employee.py
  talentmap_api/fsbid/views/employee.py
Labels: size/XS, Approved

#983 TM-5944-Agenda-Item-Delete-API
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/urls/agenda.py
  talentmap_api/fsbid/views/agenda.py
Labels: size/S, Approved

#976 TM-5960: Panel Administrator Role
  talentmap_api/common/management/commands/create_base_permissions.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/user_profile/management/commands/create_seeded_users.py
Labels: size/XS, Approved

#981 [TM-5976-5977] Maintain Separations/Assignments Integration and Refactor
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/urls/assignment_history.py
  talentmap_api/fsbid/views/assignment_history.py
Labels: size/L, Approved

#985 TM-5671, Edit Cycle Position Details
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
Labels: size/L, Approved

#987 found it
  talentmap_api/fsbid/services/bid_audit.py
Labels: size/XS, Approved

#988 [TM-5984] Maintain Assignments Remediation
  talentmap_api/fsbid/services/assignment_history.py
Labels: size/XS, Approved

#991 handle a WS fail return for Delete AI
  talentmap_api/fsbid/views/agenda.py
Labels: size/XS, Approved

#995 expose PP read to post
  talentmap_api/fsbid/views/publishable_positions.py
Labels: size/XS, Approved

#996 and the filters
  talentmap_api/fsbid/views/publishable_positions.py
Labels: size/XS

#989 [TM-5961] Deconflict FSBID and Panel Admin Features
  talentmap_api/fsbid/views/admin_panel.py
Labels: size/XS, Approved

#993 TM-5912, TM-5877, Bid Audit - Create In Category & At Grade
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/L

#990 TM-5916, TM-5915 - In Category & At Grade Bid Audit Pages
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/L, Approved

#998 wrong return code syntax
  talentmap_api/fsbid/views/agenda.py
Labels: size/XS

#1000 [TM-6144] Debug Create/Edit Maintain Assignment
  talentmap_api/fsbid/services/assignment_history.py
Labels: size/XS, Approved
