Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-06, with the labels that each got.

#1006 TM-6137 Org roles to post
  talentmap_api/fsbid/services/employee.py
Labels: size/XS, Approved

#1001 TM-6048, Run Bid Audit
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/M, Approved

#1007 [TM-6144] Maintain Assignment Post Hotfix
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/views/assignment_history.py
Labels: size/S, Approved

#1003 TM-5911, TM-5914, Delete In-Category/AtGrade
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/M

#1002 TM-5910, TM-5913 - update At Grade and In Category
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: Approved Pending Feedback, size/L, Approved

#1009 typos
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/XS

#1008 TM-6164, use display name for org, works around known FSBID issue
  talentmap_api/fsbid/services/post_access.py
Labels: size/XS, Approved

#1005 [TM-6118] Re-Integrate Projected Vacancies Read
  docker-compose-api-only.yml
  docker-compose-cloud.yml
  talentmap_api/fsbid/services/admin_projected_vacancies.py
  talentmap_api/fsbid/views/admin_projected_vacancies.py
  talentmap_api/settings.py
Labels: size/L, Approved

#1010 Revert "TM-6164, use display name for org, works around known FSBID issue"
  talentmap_api/fsbid/services/post_access.py
Labels: size/XS

#1013 use function in common file
  talentmap_api/fsbid/services/bid_audit.py
Labels: size/XS

#1011 PV Fixes
  talentmap_api/fsbid/services/admin_projected_vacancies.py
Labels: size/XS

#1014 PV Fix (Minor Change)
  talentmap_api/fsbid/services/assignment_history.py
Labels: size/XS

#999 TM-6076: Publishable Positions Re-Integrate
  docker-compose-api-only.yml
  docker-compose-cloud.yml
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/settings.py
Labels: size/L

#1017 TM-6123, TM-6126, Re-Interate Projected Vacancy
  talentmap_api/fsbid/services/admin_projected_vacancies.py
  talentmap_api/fsbid/views/admin_projected_vacancies.py
Labels: size/M, Approved

#1018 Re-Integrate with PPos for Export
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/fsbid/views/publishable_positions.py
Labels: size/S, Approved

#1015 TM-6124-Projected-Vacancies-API
  talentmap_api/fsbid/views/admin_projected_vacancies.py
Labels: size/XS, Approved

#1016 [TM-5572] Bidding Tool Integration (Edit)
  talentmap_api/fsbid/views/bidding_tool.py
Labels: size/XS, Approved

#1019 Maintain Assignment Edit Hotfix
  talentmap_api/fsbid/services/assignment_history.py
Labels: size/XS

#1004 [TM-6077] Re-Integrate Publishable Positions Edit
  talentmap_api/fsbid/services/publishable_positions.py
  talentmap_api/fsbid/views/publishable_positions.py
Labels: size/S, Approved

#1020 Publishable Positions Edit Hotfix
  talentmap_api/fsbid/views/publishable_positions.py
Labels: size/XS

#1021 Bidding Tool Hotfix
  talentmap_api/fsbid/urls/bidding_tool.py
  talentmap_api/fsbid/views/bidding_tool.py
Labels: size/S

#1022 Release 13 Hotfix
  talentmap_api/fsbid/services/bidding_tool.py
Labels: size/XS

#1025 Release 13 Main Package Migrations
  talentmap_api/fsbid/services/admin_projected_vacancies.py
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/services/bidding_tool.py
  talentmap_api/fsbid/services/bureau_exceptions.py
  talentmap_api/fsbid/services/cycle_job_categories.py
  talentmap_api/fsbid/services/job_categories.py
  talentmap_api/fsbid/services/manage_bid_seasons.py
  talentmap_api/fsbid/services/position_classifications.py
  talentmap_api/fsbid/services/post_access.py
Labels: do not merge, size/M, Approved
