Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-08, with the labels that each got.

#1049 TM-6366-Pub-Pos-Skills
  talentmap_api/fsbid/services/publishable_positions.py
Labels: size/XS, Approved

#1047 TM1 Notification Bug Fixes 1.0
  talentmap_api/fsbid/views/notifications.py
Labels: size/XS, Approved

#1048 TM-5919, Bid Book Ui
  talentmap_api/fsbid/services/bid_audit.py
Labels: size/M, Approved

#1052 Tm 6410 update panel remark mapping
  talentmap_api/fsbid/services/panel.py
Labels: size/S, Approved

#1053 TM-6365 add long desc and code to bureau filter
  talentmap_api/fsbid/services/publishable_positions.py
Labels: size/XS, Approved

#1055 HOTFIX, employee profile export
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/client.py
Labels: size/M

#1051 [TM-6371] Publishable Positions and Projected Vacancies Timestamps
  talentmap_api/fsbid/services/admin_projected_vacancies.py
Labels: size/XS, Approved

#1054 [TM-6229] TM1 Notification Send Cable
  talentmap_api/fsbid/services/notifications.py
  talentmap_api/fsbid/urls/notifications.py
  talentmap_api/fsbid/views/notifications.py
Labels: size/L, Approved

#1057 TM-6148, Bid Audit Data - HTF
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/L

#1056 TM-4844-CDO-API
  talentmap_api/fsbid/services/client.py
  talentmap_api/fsbid/views/client.py
Labels: size/S, Approved

#1060 TM-4844
  talentmap_api/fsbid/services/client.py
Labels: size/XS, Approved

#1063 Tm 6425 export button not working when exporting client list
  TM_Version.txt
  talentmap_api/fsbid/services/client.py
Labels: size/XS, Approved

#1062 update panel remark mapping (api)
  talentmap_api/fsbid/services/panel.py
Labels: size/XS, Approved

#1050 Tm 6378 search on remarks api
  talentmap_api/fsbid/services/common.py
  talentmap_api/fsbid/services/panel.py
  talentmap_api/fsbid/views/panel.py
Labels: size/S, Approved

#1066 TM-6147, Bid Book MDS
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/urls/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/M

#1067 cleanup, touchups
  talentmap_api/fsbid/services/bid_audit.py
Labels: size/XS

#1068 6147 tm final bid audit thing
  talentmap_api/fsbid/services/bid_audit.py
  talentmap_api/fsbid/views/bid_audit.py
Labels: size/XS

#1069 Tm 6425 export button not working api
  TM_Version.txt
  talentmap_api/fsbid/services/client.py
Labels: size/S, Approved

#1071 TM-6348-DETO-RWA-Bidder-Position-Searches-Integration
  talentmap_api/fsbid/services/available_positions.py
  talentmap_api/fsbid/services/projected_vacancies.py
Labels: size/XS, Approved

#1072 Revert "TM-6348-DETO-RWA-Bidder-Position-Searches-Integration"
  talentmap_api/fsbid/services/available_positions.py
  talentmap_api/fsbid/services/projected_vacancies.py
Labels: size/XS, Approved

#1073 Revert "Revert "TM-6348-DETO-RWA-Bidder-Position-Searches-Integration""
  talentmap_api/fsbid/services/available_positions.py
  talentmap_api/fsbid/services/projected_vacancies.py
Labels: size/XS, Approved
