Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-01, with the labels that each got.

#884 Update/v2 ai edit
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/services/persons.py
  talentmap_api/fsbid/views/agenda.py
Labels: size/M

#888 Fix eta/ted format
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#889 Add separate code fields with existing desc fields
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#891 Update naming convention for tf_code and lat_code
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
  talentmap_api/fsbid/views/agenda.py
Labels: size/S

#892 pull from data
  talentmap_api/fsbid/services/employee.py
Labels: size/XS

#893 Update key name
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/views/agenda.py
Labels: size/XS

#896 TM-5413 - create new assignment cycle
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
Labels: size/M

#897 update validation for separation
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS, Approved :heavy_check_mark:

#898 fix tod validation bug
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS

#895 no create metadata on edit
  talentmap_api/fsbid/services/agenda.py
Labels: question, size/M, Approved :heavy_check_mark:

#900 AIR/AIRI
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/common.py
Labels: size/L, Approved :heavy_check_mark:

#903 Fix/ai edit
  talentmap_api/fsbid/services/agenda.py
Labels: size/S

#904 Remove unnecessary mapping
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS

#899 remove validation check for travel
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS, Approved :heavy_check_mark:

#906 Fix bad date
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#908 Remove .000Z
  talentmap_api/fsbid/services/admin_panel.py
Labels: size/XS, Approved :heavy_check_mark:

#907 edge case handling for separations
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#909 Return pmseqnum on edit/create
  talentmap_api/fsbid/services/admin_panel.py
  talentmap_api/fsbid/views/admin_panel.py
Labels: size/S

#910 Fix asg seq num
  talentmap_api/fsbid/services/client.py
Labels: size/XS, Approved :heavy_check_mark:

#911 Add extra field for effective pos id key
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#913 TM-5481, TED validation for TOD of indefinite and n/a
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS, Approved :heavy_check_mark:

#915 TM-5474-Bid Tracker Update - Rename
  talentmap_api/fsbid/services/common.py
Labels: size/XS, Approved :heavy_check_mark:

#912 [TM-5071] Fix Run Panel Issues
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/admin_panel.py
  talentmap_api/fsbid/views/admin_panel.py
Labels: size/XS, Approved :heavy_check_mark:

#917 TM-4990: Panel Meetings Missing Emp Info
  talentmap_api/fsbid/services/agenda.py
Labels: dual merge, size/M, Approved :heavy_check_mark:

#918 add fallback logic for agendas with no sort date to sort
  talentmap_api/common/common_helpers.py
  talentmap_api/fsbid/services/agenda.py
Labels: WIP, size/S

#921 TM-4990: Missing Emp Info Hotfix
  talentmap_api/fsbid/services/agenda.py
Labels: size/XS, Approved :heavy_check_mark:

#920 Updated to PKG_WEBAPI_WRAP
  talentmap_api/fsbid/services/admin_panel.py
Labels: size/XS, Approved :heavy_check_mark:

#919 Change version
  TM_Version.txt
Labels: do not merge, size/XS

#922 Create Remarks Fix
  talentmap_api/fsbid/services/remark.py
Labels: size/XS

#923 Un-nest creator/updater information
  talentmap_api/fsbid/services/agenda.py
Labels: size/S

#924 TM-5479, none listed vs not applicable
  talentmap_api/fsbid/services/agenda.py
Labels: size/S, Approved :heavy_check_mark:
