Repository MetaPhase-Consulting/State-TalentMAP-API, pull requests merged in 2024-03, with the labels that each got.

#941 TM-5412, Edit Assignment Cycles
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
Labels: size/L, Approved

#946 Fix typo
  talentmap_api/fsbid/services/assignment_history.py
Labels: size/XS

#945 [TM-5541] Travel Updates
  talentmap_api/fsbid/services/agenda.py
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS, Approved

#947 5412 tm edit cycle cleanup
  talentmap_api/fsbid/services/assignment_cycles.py
Labels: size/XS, Approved

#944 [TM-5599-5656] Projected Vacancy Integration Remediation
  talentmap_api/fsbid/services/admin_projected_vacancies.py
  talentmap_api/fsbid/urls/admin_projected_vacancies.py
  talentmap_api/fsbid/views/admin_projected_vacancies.py
Labels: size/M, Approved

#950 Update/tod default
  talentmap_api/fsbid/services/assignment_history.py
  talentmap_api/fsbid/services/bid.py
  talentmap_api/fsbid/services/employee.py
  talentmap_api/fsbid/services/positions.py
Labels: size/L

#951 remove again
  talentmap_api/fsbid/services/agenda_item_validator.py
Labels: size/XS

#949 TM-5587: Manage EL Position Filtering
  talentmap_api/fsbid/services/positions.py
Labels: size/S, Approved

#953 Fix mapping
  talentmap_api/fsbid/services/positions.py
Labels: size/XS, Approved

#954 travel desc from ws
  talentmap_api/fsbid/services/agenda.py
Labels: size/S, Approved

#952 [TM-5599-5656] Projected Vacancy Integration Remediation Hotfixes
  talentmap_api/fsbid/services/admin_projected_vacancies.py
Labels: size/S, Approved

#957 Update/12.1 pkg webapi wrap
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/services/org_stats.py
  talentmap_api/fsbid/services/positions.py
Labels: size/XS, Approved

#943 TM-5645, Cycle Positions Fetch
  talentmap_api/fsbid/services/assignment_cycles.py
  talentmap_api/fsbid/urls/assignment_cycles.py
  talentmap_api/fsbid/views/assignment_cycles.py
Labels: size/L, Approved

#959 [TM-5669] Cycle Job Category Read Integration
  talentmap_api/fsbid/services/cycle_job_categories.py
  talentmap_api/fsbid/urls/cycle_job_categories.py
  talentmap_api/fsbid/views/cycle_job_categories.py
  talentmap_api/urls.py
Labels: size/L, Approved, Changes Requested

#962 Merge cycle hotfix
  talentmap_api/fsbid/services/assignment_cycles.py
Labels: size/XS, Approved
